public class ATNQConstants {
    
    public static final String JSON_DESERIALIZATION_ERROR = 'SF_JSN_ERR_001';
    public static final String JSON_DESERIALIZATION_ERROR_MSG = 'deserialization of input json failed';
    public static final String JSON_SERIALIZATION_ERROR = 'SF_JSN_ERR_002';
    public static final String JSON_SERIALIZATION_ERROR_MSG = 'Serialization of input json failed';
    
    public static final String USER_NOT_FOUND_ERROR = 'SF_USR_ERR_001';
    public static final String USER_NOT_FOUND_ERROR_MSG = 'User Not Found';
    public static final String USER_ALREADY_EXISTS_ERROR = 'SF_USR_ERR_002';
    public static final String USER_FIELD_VALIDATION_ERROR = 'SF_USR_ERR_103';
    public static final String USER_REQUIRED_FIELD_MISSING_ERROR = 'SF_USR_ERR_104';
    public static final String USER_REQUIRED_FIELD_MISSING_ERROR_USER_NAME = 'SF_USR_ERR_105';
    public static final String USER_FIELD_VALIDATION_ERROR_USER_NAME = 'SF_USR_ERR_106';
    public static final String USER_ADOES_NOT_EXISTS_ERROR = 'SF_USR_ERR_007';

    public static final String ATNQ_ACCOUNT_NOT_FOUND_ERROR = 'SF_AAC_ERR_001';
    public static final String ATNQ_ACCOUNT_ALREADY_EXISTS_ERROR = 'SF_AAC_ERR_002';
    public static final String ATNQ_ACCOUNT_FIELD_VALIDATION_ERROR = 'SF_AAC_ERR_003';
    public static final String ATNQ_ACCOUNT_REQUIRED_FIELD_MISSING_ERROR = 'SF_AAC_ERR_004';
    public static final String ATNQ_ACCOUNT_PROCESSING_EXCEPTION = 'SF_AAC_ERR_005';
    public static final String ATNQ_ACCOUNT_REQUIRED_FIELD_MISSING_ACCOUNT_NAME = 'SF_AAC_ERR_006';
    public static final String ATNQ_ACCOUNT_FIELD_VALIDATION_ERROR_ACCOUNT_NAME = 'SF_AAC_ERR_007';
    
    public static final String ATNQ_PAYMENTPROFILE_PROCESSING_EXCEPTION = 'SF_APP_ERR_001';
    public static final String ATNQ_VHR_PROCESSING_EXCEPTION = 'SF_AVHR_ERR_001';
 
    public static final String ATNQ_PAYMENT_PROFILE_ERROR = 'SF_PPF_ERR_000';
    
    public static final String ATNQ_SUBSCRIPTION_ERROR = 'SF_SUB_ERR_000';
    
    public static final String ATNQ_SUBSCRIPTION_ITEM_ERROR = 'SF_SBI_ERR_000';
    
    public static final String ATNQ_THIRD_PARTY_ITEM_ERROR = 'SF_TPI_ERR_000';
    
    public static final String ATNQ_REGISTRATION_OBJECT_CREATION_ERROR = 'SF_ROC_ERR_100';
    
    public static final String ATNQ_USER_APPLICATION_SETTINGS_ERROR = 'SF_UAS_ERR_000';
    
    public static final String ATNQ_PRODUCT_CODE_AAX = 'AAX';
    public static final String ATNQ_PRODUCT_NAME_AAX = 'AAX Integration';
    public static final String ATNQ_PRODUCT_CODE_CARFAX = 'CF';
    public static final String ATNQ_PRODUCT_Name_CARFAX = 'CarFax';
    public static final String ATNQ_PRODUCT_CODE_BB = 'BB';
    public static final String ATNQ_PRODUCT_NAME_BB = 'Black Book';
    public static final String ATNQ_PRODUCT_CODE_AC = 'AC';
    public static final String ATNQ_PRODUCT_NAME_AC = 'AutoCheck';
    public static final String ATNQ_PRODUCT_CODE_GALVES = 'GALVES';
    public static final String ATNQ_PRODUCT_NAME_GALVES = 'GALVES';
    public static final String ATNQ_PRODUCT_CODE_KBB = 'KBB';
    public static final String ATNQ_PRODUCT_NAME_KBB = 'Kelly Blue Book';
    public static final String ATNQ_PRODUCT_CODE_NADA = 'NADA';
    public static final String ATNQ_PRODUCT_NAME_NADA = 'NADA';
    public static final String ATNQ_PRODUCT_CODE_MR = 'MR';
    public static final String ATNQ_PRODUCT_NAME_MR = 'Market Report';
    public static final String ATNQ_PRODUCT_CODE_APG = 'APG';
    public static final String ATNQ_PRODUCT_NAME_APG = 'Autoniq Profit Guide';
    public static final String ATNQ_PRODUCT_CODE_MMR = 'MMR';
    public static final String ATNQ_PRODUCT_NAME_MMR = 'Manheim Market Report';
    public static final String ATNQ_PRODUCT_CODE_DISC = 'DISC';
    public static final String ATNQ_PRODUCT_NAME_DISC = 'Discount';
    
    
}