global class AutoniqMyAccountSignupRequest {
	public AutoniqMyAccountSignupRequest() {
		
	}
	public List <string> features;
	public string login;
	public string passwd;
	public string passwdConfirm;
	public string email;
	public string firstName;
	public string lastName;
	public string dealership;
	public string auctionAccessId;
	public string mobileDeviceType;
	public string phone;
	public string phone2;
	public string country;
	public string address;
	public string city;
	public string state;
	public string postalCode;
	public string promoCode;
	public string ccNumber;
	public string ccExpiration;
	public string referredBy;
	public string ccExpMonth;
	public string ccExpYear;
	public string recaptcha;
}