global class AutoniqMyAccountUpdateGeneralRequest {
    public AutoniqMyAccountUpdateGeneralRequest() {
        
    }
    public string contactId;
    public boolean general;
    public string dealership;
    public string address;
    public string city;
    public string state;
    public string postalCode;
    public string email;
    public string phone;
    public string homeRegionZipCode;
    public string deviceType;
    public string menuStyle;
    public string homeRegionSelected;
    public string peBBTable;
    public string peKBBTable;
    public string peNADATable;
}