global class AutoniqMyAccountUpdatePaymentInfoRequest {
    public AutoniqMyAccountUpdatePaymentInfoRequest() {
        
    }

    public boolean cc;
    public string ccContactId;
    public string ccFirstName;
    public string ccLastName;
    public string ccAddress;
    public string ccCity;
    public string ccState;
    public string ccCountry;
    public string ccPostalCode;
    public string ccNumber;
    public string ccExpiresMonth;
    public string ccExpiresYear;
}