/*
* (c) 2016 Appirio, Inc.
* 
* Apex Class Name   : Constants
*
* Description       : Class to store constants.
*
* 21 Nov 2016         Ankita Sharma(Appirio)   Original (T-548983  ) - Please see the Task description for more details.
*
*/
public class Constants {

    public static final String SYS_ADMIN = 'System Administrator';
    
    public static final String AFC_DEL_SUP = 'AFC Delegated Support';
    
    public static final String AD_DEL_SUP = 'ADESA Delegated Support';

    public static final String DATA_MIGRAT = 'Data Migration';

    public static final string ORDER_STATUS_DRAFT = 'Draft';

    public static final string ORDER_STATUS_ACTIVATED = 'Activated';

    public static final string ORDER_STATUS_PENDING = 'Pending';

    public static final string PRODUCT_CODE_FEE = 'FEE';
    
    public static final string SUBSCRIPTION_TERM_MONTHLY = 'Monthly';
    
    public static final string SUBSCRIPTION_TERM_ANNUAL = 'Annual';
    
    public static final String SUBSCRIPTION_STATUS_ACTIVE = 'Active';
}