@isTest
public with sharing class TestStewardshipMonitor {
	public TestStewardshipMonitor() {
	}

	static testMethod void testStewardshipMonitorJob(){
        //Account a = new Account(Name='Test Account', MDM_Refresh_Date__c=System.now(),Integration_Id__c='123456789');
        //insert a;
        //Account b = new Account(Name='Test Account2', MDM_Refresh_Date__c=System.now(),Integration_Id__c='123456789');
        //insert b;
        //Test.startTest();
        //    System.assertEquals(1,[select id from Case where Subject = 'Duplicate Integration Id: 123456789' limit 1].size());
        //Test.stopTest();
	}

}